// Topics verified against Microsoft Learn on 7 October 2026.
// Session duration includes reading, active recall and a brief dashboard log.
const moduleUrl = slug => `https://learn.microsoft.com/en-us/training/modules/${slug}/`;
const guide = 'https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/az-900';
const practice = 'https://learn.microsoft.com/en-us/credentials/certifications/azure-fundamentals/';
const project = moduleUrl('guided-project-deploy-static-website-blob-storage');
const session = (title, resource, goal, taskId) => ({title,resource,goal,taskId});
export const schedule = [
  session('Cloud refresher & Azure architecture kickoff', moduleUrl('describe-core-architectural-components-of-azure'), 'Your three cloud-concepts modules and assessments are already completed (verified in Microsoft Learn, March 2026). Spend 10 minutes recalling shared responsibility, cloud benefits and IaaS/PaaS/SaaS without notes. Use the remaining time to begin Azure regions, availability zones and subscriptions; log any recall gaps.', 'az-services'),
  session('Apply regions, zones & resource groups', moduleUrl('describe-core-architectural-components-of-azure'), 'Continue the new architecture module. Draw a region/zone diagram and the management-group, subscription, resource-group and resource hierarchy. Explain where the support app belongs and complete the module assessment when ready.', 'az-services'),
  session('Support-app service choices & reliability', moduleUrl('describe-azure-compute-networking-services'), 'Apply your completed cloud-benefits and service-types learning to the capstone: compare two hosting choices, identify your security responsibilities, and describe one availability and scaling decision. Begin the compute module; revisit completed material only for specific recall gaps.', 'az-services'),
  session('Architecture scenarios & knowledge check', moduleUrl('describe-core-architectural-components-of-azure'), 'Apply the architecture module to three scenarios: a regional outage, organizing development and production resources, and separating billing from access. Explain your choices without notes, finish outstanding units and record assessment gaps.', 'az-services'),
  session('Compute: VMs, containers, Functions & web apps', moduleUrl('describe-azure-compute-networking-services'), 'Compare Azure compute and application-hosting options. Pick an initial hosting option for the synthetic-data support app and explain two tradeoffs. Use a comparison table rather than memorizing product names.', 'az-services'),
  session('Networking & public/private endpoints', moduleUrl('describe-azure-networking-services'), 'Study virtual networks, subnets, peering, DNS and hybrid connectivity. Sketch how a browser reaches your support app and database. Explain public versus private endpoints and one access boundary.', 'az-services'),
  session('Week 1 review & next priorities', guide, 'Spend 15 minutes recalling cloud concepts and service choices without notes, 10 minutes reviewing confusing topics, and 5 minutes saving a weekly review and three manageable priorities in Learning desk. Carry gaps forward within next week’s five-hour limit.', 'az-concepts'),
  session('Storage, tiers, redundancy & migration', moduleUrl('describe-azure-storage-services'), 'Compare Blob, Files and other Azure storage options; review tiers, redundancy and migration tools. Choose where the demonstration app should keep static content and documents. Record why replication is not a substitute for a recovery plan.', 'az-services'),
  session('Identity, authentication & Entra ID', moduleUrl('describe-azure-identity-access-security'), 'Study Entra ID, authentication, SSO, MFA, passwordless access and external identities. Explain authentication versus authorization using agent and manager roles in the support app.', 'az-governance'),
  session('RBAC, Conditional Access & Zero Trust', moduleUrl('describe-azure-identity-access-security'), 'Finish the identity and security module. Compare RBAC and Conditional Access, then describe Zero Trust, defense in depth and Defender for Cloud. Draft least-privilege access for agent and manager roles without changing any real workplace permissions.', 'az-governance'),
  session('Cloud costs, tags & your R300 lab envelope', moduleUrl('describe-cost-management-azure'), 'Study cost drivers, the pricing calculator, cost management and tags. Estimate one short-lived demonstration deployment and record it in the budget tracker. A budget alert does not stop charges; write down which resources must be deleted.', 'az-governance'),
  session('Governance: Policy, locks & Purview', moduleUrl('describe-features-tools-azure-for-governance-compliance'), 'Compare Azure Policy, resource locks and Microsoft Purview. Explain which controls enforce configuration, prevent accidental changes and help with governance. Complete the module assessment and note one useful capstone control.', 'az-governance'),
  session('Portal, CLI, PowerShell, ARM & Azure Arc', moduleUrl('describe-features-tools-manage-deploy-azure-resources'), 'Study Azure management and deployment tools. Compare Portal, Cloud Shell, CLI and PowerShell. Explain infrastructure as code, ARM templates and Azure Arc. Draft the steps to create and remove a demonstration resource group.', 'az-governance'),
  session('Week 2 review & security recap', guide, 'Recall storage, identity and governance without notes. Revisit missed module questions, record your weekly reflection and set three priorities for the deployment week. Check remaining lab budget before committing to cloud resources.', 'az-governance'),
  session('Monitor, Advisor, Service Health & logs', moduleUrl('describe-monitoring-tools-azure'), 'Study Azure Advisor, Service Health, Monitor, Log Analytics and Application Insights. Match each to a practical question: optimization, platform incident, app failure or request performance. Sketch the checks you will use for the demo.', 'az-governance'),
  session('Prepare the static-site deployment safely', project, 'Read the guided project before provisioning. Check account eligibility, selected region, pricing estimate and cleanup steps. Use synthetic content only. If your budget cannot cover the exercise, implement locally and document the intended Azure setup instead.', 'az-deploy'),
  session('Build the synthetic-data site locally', project, 'Prepare a small static customer-support information page using fictional records. Run it locally and check links and readability. Keep all customer, employer and account secrets out of the demonstration content.', 'az-deploy'),
  session('Deploy the static site on Azure', project, 'Follow the official Blob Storage static-site guided project within the approved lab envelope. Verify the website endpoint. If cloud access or pricing blocks you, save the blocker and continue the local implementation rather than purchasing extra services.', 'az-deploy'),
  session('Verify, troubleshoot & explain your deployment', project, 'Test the site from a browser, check the published content, and troubleshoot a deliberately missing page or broken asset. Explain the compute/storage choices, public access and limitations. Save screenshots or a demonstration link as evidence.', 'az-deploy'),
  session('Record costs, capture evidence & clean up', project, 'Write a short deployment note covering service choices, access boundaries, estimated versus actual cost and what you learned. Delete unneeded Azure resources and check the resource group is clear. Complete the roadmap milestone only when its criteria are demonstrated.', 'az-deploy'),
  session('Week 3 review & budget check', guide, 'Review deployment evidence and remaining budget. Identify two AZ-900 topics you still cannot explain clearly. Save a weekly check-in, export a dashboard backup, and plan revision within next week’s five-hour limit.', 'az-deploy'),
  session('AZ-900 objective audit & recall', guide, 'Compare your notes with every objective in the current AZ-900 study guide. Mark confident and weak topics. Explain three cloud/service/governance scenarios without notes; choose the most important gaps to revise.', 'az-readiness'),
  session('Practice assessment 1 & error notes', practice, 'Open the official free Practice Assessment from the certification page. Answer before checking explanations. Save your percentage and weak domains as practice evidence. Aim for 85% as a personal readiness target, not an official pass prediction.', 'az-readiness'),
  session('Revise weak architecture & service topics', guide, 'Revisit architecture, compute, networking or storage topics missed in assessment 1. Write why the correct choices fit the scenario and why the alternatives do not. If these areas were strong, revisit your weakest domain instead.', 'az-readiness'),
  session('Revise weak identity & governance topics', guide, 'Review authentication, authorization, RBAC, Policy, locks, costs and monitoring where needed. Explain five distinctions from memory. Use your practice-error notes rather than repeatedly memorizing the same questions.', 'az-readiness'),
  session('Practice assessment 2 & readiness check', practice, 'Take a second official assessment after the revision days. Save the result separately with the date. Compare the two spaced attempts; readiness also requires explaining decisions and demonstrating practical skills. Do not mark the certification passed from practice scores.', 'az-readiness'),
  session('Close gaps & check exam affordability', practice, 'Resolve remaining weak topics, rehearse the exam interface and check current objectives and the South African checkout price. Record an exam quote in the dashboard. Book only if prepared and within your budget; otherwise defer and continue learning.', 'az-readiness'),
  session('Month 1 review & next-phase preparation', guide, 'Review progress, practice scores, evidence and spending. Save next week’s three priorities for secure software delivery, export a backup and decide whether to carry AZ-900 gaps forward. An exam booking or pass must be recorded separately.', 'az-readiness'),
].map((row, index) => ({...row,day:index+1,minutes:index%7===6?30:45}));

export const calendarDefaults = { startDate:'2026-10-12', startTime:'09:00', timeZone:'Africa/Johannesburg', reminderMinutes:10 };
